name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Check build status
        id: check_status
        run: |
          STATUS=$(jq -r '.["build-status"]' ./deployer.json)
          echo "::set-output name=status::$STATUS"

      - name: Run build if status is valid
        if: steps.check_status.outputs.status == 'Valid'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run build -- --config electron-builder.yaml

      - name: Publish artifact
        if: steps.check_status.outputs.status == 'Valid'
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/